// SPDX-License-Identifier: MIT OR Apache-2.0
#![doc = "Hash and Pedersen-EC commitments for the tecdsa threshold ECDSA library."]

use elliptic_curve::{sec1::ModulusSize, FieldBytes, FieldBytesSize, PrimeField};
use rand_core::CryptoRngCore;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use tecdsa_curve::TecdsaCurve;

// ──────────────────────────────────────────────────────────────────────────────
// Hash commitment
// ──────────────────────────────────────────────────────────────────────────────

/// A hash-based commitment `H(nonce ‖ message)`.
///
/// The nonce is generated by the committer, kept secret until opening, and
/// returned alongside the message to verify.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HashCommitment {
    hash: [u8; 32],
}

impl HashCommitment {
    /// Commit to `message` using a fresh random nonce.
    ///
    /// Returns `(commitment, nonce)`. The nonce is the opening witness.
    pub fn commit(message: &[u8], rng: &mut impl CryptoRngCore) -> (Self, [u8; 32]) {
        let mut nonce = [0u8; 32];
        rng.fill_bytes(&mut nonce);
        let hash = Sha256::new()
            .chain_update(nonce)
            .chain_update(message)
            .finalize()
            .into();
        (Self { hash }, nonce)
    }

    /// Verify an opening `(message, nonce)` against this commitment.
    #[must_use]
    pub fn verify(&self, message: &[u8], nonce: &[u8; 32]) -> bool {
        let expected: [u8; 32] = Sha256::new()
            .chain_update(nonce)
            .chain_update(message)
            .finalize()
            .into();
        self.hash == expected
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Pedersen elliptic-curve commitment
// ──────────────────────────────────────────────────────────────────────────────

/// Pedersen EC commitment `C = value·G + randomness·H`.
///
/// `G` is the standard group generator; `H` is the NUMS auxiliary point
/// provided by [`TecdsaCurve::nums_pedersen_h`].  The committer keeps
/// `randomness` secret and reveals it together with `value` to open.
#[derive(Debug, Clone)]
pub struct PedersenCommitment<C: TecdsaCurve>
where
    FieldBytesSize<C>: ModulusSize,
{
    /// The public commitment point `value·G + randomness·H`.
    pub point: C::ProjectivePoint,
    /// The blinding scalar (secret opening witness).
    pub randomness: C::Scalar,
}

impl<C: TecdsaCurve> PedersenCommitment<C>
where
    FieldBytesSize<C>: ModulusSize,
    C::Scalar: PrimeField<Repr = FieldBytes<C>>,
{
    /// Commit to a scalar `value` using a fresh blinding factor.
    pub fn commit_scalar(value: &C::Scalar, rng: &mut impl CryptoRngCore) -> Self {
        let randomness = C::random_scalar(rng);
        let g = C::generator();
        let h = C::nums_pedersen_h();
        // C = value·G + randomness·H
        let point = g * value + h * randomness;
        Self { point, randomness }
    }

    /// Verify that this commitment opens to `value`.
    #[must_use]
    pub fn verify_scalar(&self, value: &C::Scalar) -> bool {
        let expected = C::generator() * value + C::nums_pedersen_h() * self.randomness;
        self.point == expected
    }
}
