// SPDX-License-Identifier: MIT OR Apache-2.0
//! Proactive refresh protocol for KGG24 (Section 6).
//!
//! Re-randomizes both parties' additive shares without changing the joint
//! public key. This enables proactive security: even if an adversary obtains
//! a party's share at some point in time, a subsequent refresh renders it
//! useless.
//!
//! ## Protocol
//!
//! 1. **Coin flip**: Both parties jointly sample `r <- Z_q` (simplified here
//!    as a trusted random value since we are not implementing the full
//!    coin-flipping sub-protocol with commitments).
//!
//! 2. **P_1 updates**:
//!    - `x_1_new = x_1 - r mod q`
//!    - Generate fresh Paillier keypair `(N', sk')`
//!    - Sample noise `t' <- [2^{tau + 2*kappa}]`
//!    - `C' = Enc_{N'}(x_1_new + t' * q)`
//!    - Generate fresh Pi_GCD, Pi_eq proofs (deferred)
//!    - Send `(N', C')` to P_2
//!
//! 3. **P_2 updates**:
//!    - `x_2_new = x_2 + r mod q`
//!    - Verify proofs (deferred), store new `(N', C')`
//!
//! After refresh: `x_1_new + x_2_new = (x_1 - r) + (x_2 + r) = x_1 + x_2 = x`

use elliptic_curve::{sec1::ModulusSize, FieldBytes, FieldBytesSize, PrimeField};
use rand_core::CryptoRngCore;
use tecdsa_curve::TecdsaCurve;
use tecdsa_paillier::{
    backend::Integer,
    zk::{correct_key_ni::NICorrectKeyProof, pi_eq::PiEqProof},
    BigIntExt,
};

use crate::{
    error::Kgg24Error,
    key_share::{Kgg24Party1KeyShare, Kgg24Party2KeyShare},
    keygen::curve_order,
};

/// Security parameter tau.
const TAU: u32 = 256;
/// Statistical security parameter kappa.
const KAPPA: u32 = 80;

/// Refresh message from P_1 to P_2 containing new Paillier key, ciphertext, and proofs.
pub struct RefreshMsg<C: TecdsaCurve>
where
    FieldBytesSize<C>: ModulusSize,
{
    /// New Paillier encryption key.
    pub ek: tecdsa_paillier::EncryptionKey,
    /// New ciphertext `C' = Enc_{N'}(x_1_new + t' * q)`.
    pub c_key: tecdsa_paillier::Ciphertext,
    /// Pi_GCD proof: gcd(N', phi(N')) = 1.
    pub pi_gcd: NICorrectKeyProof,
    /// Pi_eq proof: loose consistency between C' and X1_new.
    pub pi_eq: PiEqProof<C>,
    /// X1_new = x_1_new * G (needed for Pi_eq verification).
    pub x1_new_point: C::ProjectivePoint,
}

/// Perform a complete proactive refresh of both parties' key shares.
///
/// This is a convenience function that runs the full refresh protocol
/// sequentially. Both parties' shares are updated in-place such that
/// `x_1_new + x_2_new = x_1 + x_2 = x` and the public key remains unchanged.
///
/// In a real deployment, the coin-flip sub-protocol would be interactive.
/// Here we use a trusted random `r` generated by the RNG.
pub fn refresh<C: TecdsaCurve>(
    p1_key: &mut Kgg24Party1KeyShare<C>,
    p2_key: &mut Kgg24Party2KeyShare<C>,
    rng: &mut impl CryptoRngCore,
) -> Result<(), Kgg24Error>
where
    FieldBytesSize<C>: ModulusSize,
    C::Scalar: PrimeField<Repr = FieldBytes<C>>,
{
    // Step 1: Coin flip -- jointly sample r <- Z_q
    // (simplified: trusted random from RNG)
    let r = C::random_scalar(rng);

    // Step 2: P_1 updates
    let refresh_msg = party1_refresh::<C>(p1_key, r, rng)?;

    // Step 3: P_2 verifies proofs and updates
    party2_refresh::<C>(p2_key, r, &refresh_msg)?;

    // Sanity check: public keys should still match
    assert_eq!(
        p1_key.public_key, p2_key.public_key,
        "public keys diverged after refresh"
    );

    Ok(())
}

/// Party 1 refresh: update secret share, generate new Paillier keypair, encrypt,
/// and produce Pi_GCD and Pi_eq proofs.
fn party1_refresh<C: TecdsaCurve>(
    key_share: &mut Kgg24Party1KeyShare<C>,
    r: C::Scalar,
    rng: &mut impl CryptoRngCore,
) -> Result<RefreshMsg<C>, Kgg24Error>
where
    FieldBytesSize<C>: ModulusSize,
    C::Scalar: PrimeField<Repr = FieldBytes<C>>,
{
    // x_1_new = x_1 - r mod q
    let x1_new = key_share.secret_share - r;
    let x1_new_point = C::generator() * x1_new;

    // Generate fresh Paillier keypair
    let dk_new = tecdsa_paillier::keygen(rng)
        .map_err(|e| Kgg24Error::Refresh(format!("Paillier keygen failed: {e}")))?;
    let ek_new = dk_new.encryption_key().clone();

    // Sample noise t' from [0, 2^{tau + 2*kappa})
    let q_int = curve_order::<C>();
    let noise_bound = Integer::two_pow(TAU + 2 * KAPPA);
    let t_prime = noise_bound.sample_below_ref(rng);

    // Compute x_hat_1_new = x_1_new + t' * q
    let x1_new_bytes = x1_new.to_repr();
    let x1_new_int = tecdsa_paillier::backend::Integer::from_bytes_msf(x1_new_bytes.as_ref());
    let x_hat_1_new = x1_new_int + t_prime * q_int;

    // Encrypt: C' = Enc_{N'}(x_hat_1_new; rho)
    let (c_key_new, enc_nonce) = dk_new.encrypt_with_random(rng, &x_hat_1_new).map_err(|e| {
        Kgg24Error::Refresh(format!(
            "Paillier encryption of refreshed share failed: {e}"
        ))
    })?;

    // Create Pi_GCD proof (proves knowledge of factorization of N')
    let pi_gcd = NICorrectKeyProof::prove(&dk_new, b"kgg24-correct-key-challenge");

    // Create Pi_eq proof (loose consistency: C' encrypts x_hat_1_new, X1_new = x1_new * G)
    let ssid = b"kgg24-refresh";
    let pi_eq = PiEqProof::<C>::prove(
        ssid,
        &ek_new,
        &dk_new,
        &c_key_new,
        &x1_new_point,
        &x_hat_1_new,
        &enc_nonce,
        rng,
    );

    // Update P_1's key share in place
    key_share.secret_share = x1_new;
    key_share.dk = dk_new;

    Ok(RefreshMsg {
        ek: ek_new,
        c_key: c_key_new,
        pi_gcd,
        pi_eq,
        x1_new_point,
    })
}

/// Party 2 refresh: verify Pi_GCD and Pi_eq proofs, then update secret share
/// and store new Paillier parameters.
fn party2_refresh<C: TecdsaCurve>(
    key_share: &mut Kgg24Party2KeyShare<C>,
    r: C::Scalar,
    refresh_msg: &RefreshMsg<C>,
) -> Result<(), Kgg24Error>
where
    FieldBytesSize<C>: ModulusSize,
    C::Scalar: PrimeField<Repr = FieldBytes<C>>,
{
    // Step 1: Verify Pi_GCD proof
    if !refresh_msg
        .pi_gcd
        .verify(&refresh_msg.ek, b"kgg24-correct-key-challenge")
    {
        return Err(Kgg24Error::PiGcdVerification(
            "Refresh: Pi_GCD proof verification failed".into(),
        ));
    }

    // Step 2: Verify Pi_eq proof
    let ssid = b"kgg24-refresh";
    if !refresh_msg.pi_eq.verify(
        ssid,
        &refresh_msg.ek,
        &refresh_msg.c_key,
        &refresh_msg.x1_new_point,
    ) {
        return Err(Kgg24Error::PiEqVerification(
            "Refresh: Pi_eq proof verification failed".into(),
        ));
    }

    // Step 3: Verify X1_new is consistent with public key update
    // X1_new should equal X1_old - r*G, and we know the public key = X1_old + X2_old
    // After refresh: X1_new + X2_new = (X1_old - r*G) + (X2_old + r*G) = X1_old + X2_old
    let x2_new = key_share.secret_share + r;
    let x2_new_point = C::generator() * x2_new;
    let expected_pk = refresh_msg.x1_new_point + x2_new_point;
    if expected_pk != key_share.public_key {
        return Err(Kgg24Error::Refresh(
            "Refresh: X1_new + X2_new does not match the existing public key".into(),
        ));
    }

    // All checks passed; update P_2's key share in place
    key_share.secret_share = x2_new;
    key_share.ek = refresh_msg.ek.clone();
    key_share.c_key = refresh_msg.c_key.clone();

    Ok(())
}

#[cfg(test)]
mod tests {
    use k256::Secp256k1;

    use super::*;
    use crate::keygen::trusted_dealer_keygen;

    #[test]
    fn refresh_preserves_public_key() {
        let mut rng = rand_core::OsRng;
        let (mut p1, mut p2) = trusted_dealer_keygen::<Secp256k1>(&mut rng);

        let original_pk = p1.public_key;

        refresh(&mut p1, &mut p2, &mut rng).expect("refresh should succeed");

        // Public key unchanged
        assert_eq!(p1.public_key, original_pk);
        assert_eq!(p2.public_key, original_pk);

        // Shares still sum to the same secret
        let x = p1.secret_share + p2.secret_share;
        let expected_pk = Secp256k1::generator() * x;
        assert_eq!(p1.public_key, expected_pk);
    }

    #[test]
    #[ignore = "redundant refresh variant"]
    fn refresh_changes_shares() {
        let mut rng = rand_core::OsRng;
        let (mut p1, mut p2) = trusted_dealer_keygen::<Secp256k1>(&mut rng);

        let old_x1 = p1.secret_share;
        let old_x2 = p2.secret_share;

        refresh(&mut p1, &mut p2, &mut rng).expect("refresh should succeed");

        // Individual shares should have changed (with overwhelming probability)
        assert_ne!(p1.secret_share, old_x1);
        assert_ne!(p2.secret_share, old_x2);
    }

    #[test]
    #[ignore = "redundant refresh variant"]
    fn multiple_refreshes_preserve_key() {
        let mut rng = rand_core::OsRng;
        let (mut p1, mut p2) = trusted_dealer_keygen::<Secp256k1>(&mut rng);

        let original_pk = p1.public_key;

        for _ in 0..5 {
            refresh(&mut p1, &mut p2, &mut rng).expect("refresh should succeed");
        }

        assert_eq!(p1.public_key, original_pk);
        assert_eq!(p2.public_key, original_pk);

        let x = p1.secret_share + p2.secret_share;
        let expected_pk = Secp256k1::generator() * x;
        assert_eq!(p1.public_key, expected_pk);
    }

    #[test]
    #[ignore = "redundant refresh variant"]
    fn refresh_updates_paillier_ciphertext() {
        let mut rng = rand_core::OsRng;
        let (mut p1, mut p2) = trusted_dealer_keygen::<Secp256k1>(&mut rng);

        refresh(&mut p1, &mut p2, &mut rng).expect("refresh should succeed");

        // Verify the new ciphertext decrypts to x_1_new mod q
        let decrypted = p1.dk.decrypt(&p2.c_key).expect("decryption failed");
        let q_int = curve_order::<Secp256k1>();
        let decrypted_mod_q = decrypted.modulo(&q_int);

        let x1_bytes = p1.secret_share.to_repr();
        let x1_int = tecdsa_paillier::backend::Integer::from_bytes_msf(x1_bytes.as_ref());
        assert_eq!(decrypted_mod_q, x1_int);
    }
}
