// SPDX-License-Identifier: MIT OR Apache-2.0
//! Zero-knowledge range proofs for the Multiplicative-to-Additive (MtA) protocol.
//!
//! These proofs are described in Appendix A of <https://eprint.iacr.org/2019/114.pdf>
//! (GG18/GG20). They use Ring-Pedersen commitments with auxiliary parameters
//! $(N', h_1, h_2)$ to prove that a Paillier plaintext is in a bounded range.
//!
//! Two proofs are provided:
//!
//! - **`AliceProof`**: Alice sends $C = \text{Enc}_N(a; r)$ and proves
//!   $|a| < q^3$ where $q$ is the EC group order.
//!
//! - **`BobProof`**: Bob receives $C_a = \text{Enc}_N(a)$, computes
//!   $C_b = b \cdot C_a \oplus \text{Enc}_N(\beta'; r)$ and proves knowledge
//!   of $(b, \beta', r)$ with $|b| < q^3$. An extended variant `BobProofExt`
//!   additionally proves $B = bG$ on the elliptic curve.
//!
//! The proofs are non-interactive via the Fiat-Shamir transform (SHA-256).

#![allow(non_snake_case)]

use elliptic_curve::{
    group::GroupEncoding, sec1::ModulusSize, CurveArithmetic, FieldBytes, FieldBytesSize,
    PrimeField,
};
use fast_paillier::backend::{BigIntExt, Integer};
use rug::Complete;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use tecdsa_curve::TecdsaCurve;

// ---------------------------------------------------------------------------
// Serde helper for Integer (MSF byte encoding)
// ---------------------------------------------------------------------------

mod ser_integer {
    use fast_paillier::backend::{BigIntExt, Integer};
    use serde::{Deserialize, Deserializer, Serialize, Serializer};

    pub fn serialize<S: Serializer>(val: &Integer, serializer: S) -> Result<S::Ok, S::Error> {
        val.to_bytes_msf().serialize(serializer)
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<Integer, D::Error> {
        let bytes = Vec::<u8>::deserialize(deserializer)?;
        Ok(Integer::from_bytes_msf(&bytes))
    }
}

use super::pdl_slack::{commitment_unknown_order, pow_mod_signed, sample_below};
use crate::conv::{group_order_integer, integer_to_scalar};

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/// Error type for MtA range proof verification failures.
#[derive(Debug, thiserror::Error)]
pub enum MtaRangeError {
    /// Verification of Alice's range proof failed.
    #[error("Alice MtA range proof verification failed")]
    AliceVerify,
    /// Verification of Bob's range proof failed.
    #[error("Bob MtA range proof verification failed")]
    BobVerify,
}

// ---------------------------------------------------------------------------
// NTilde parameters (shared auxiliary commitment parameters)
// ---------------------------------------------------------------------------

/// Ring-Pedersen auxiliary parameters $(N', h_1, h_2)$ used as commitment
/// parameters in MtA range proofs. These are generated by a third party
/// (or the verifier) and shared publicly.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct NTildeParams {
    /// RSA modulus $N' = p' q'$.
    #[serde(with = "ser_integer")]
    pub N_tilde: Integer,
    /// First base $h_1$.
    #[serde(with = "ser_integer")]
    pub h1: Integer,
    /// Second base $h_2 = h_1^\lambda \bmod N'$.
    #[serde(with = "ser_integer")]
    pub h2: Integer,
}

// ============================================================================
// Alice's proof
// ============================================================================

/// Non-interactive range proof that Alice's Paillier ciphertext encrypts
/// a value $a$ with $|a| < q^3$.
///
/// **Statement:** $(C, N, N', h_1, h_2)$ where $C = \text{Enc}_N(a; r)$.
///
/// **Witness:** $(a, r)$.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AliceProof {
    z: Integer,
    e: Integer,
    s: Integer,
    s1: Integer,
    s2: Integer,
}

impl AliceProof {
    /// Generate Alice's range proof.
    ///
    /// # Parameters
    /// - `a`: the plaintext value
    /// - `cipher`: the Paillier ciphertext $C = \text{Enc}_N(a; r)$
    /// - `ek_n`: the Paillier modulus $N$
    /// - `ek_nn`: the Paillier modulus squared $N^2$
    /// - `ntilde`: the Ring-Pedersen auxiliary parameters
    /// - `r`: the Paillier encryption randomness
    /// - `rng`: a cryptographic RNG
    pub fn prove<C>(
        a: &Integer,
        cipher: &Integer,
        ek_n: &Integer,
        ek_nn: &Integer,
        ntilde: &NTildeParams,
        r: &Integer,
        rng: &mut impl rand_core::CryptoRngCore,
    ) -> Self
    where
        C: TecdsaCurve,
        FieldBytesSize<C>: ModulusSize,
        <C as CurveArithmetic>::Scalar: PrimeField<Repr = FieldBytes<C>>,
    {
        let q = group_order_integer::<C>();
        let q3 = (&q * &q).complete() * &q;
        let q_N_tilde = (&q * &ntilde.N_tilde).complete();
        let q3_N_tilde = (&q3 * &ntilde.N_tilde).complete();

        // Round 1: sample blinding values and compute commitments
        let alpha = sample_below(&q3, rng);
        let beta = Integer::sample_in_mult_group_of(rng, ek_n);
        let gamma = sample_below(&q3_N_tilde, rng);
        let rho = sample_below(&q_N_tilde, rng);

        // z = h1^a * h2^rho mod N_tilde
        let z = commitment_unknown_order(&ntilde.h1, &ntilde.h2, &ntilde.N_tilde, a, &rho);

        // u = (1 + N)^alpha * beta^N mod N^2
        //   = (1 + alpha*N) * beta^N mod N^2
        let g_paillier = ek_n + Integer::one();
        let u = {
            // (1 + N)^alpha = (1 + alpha*N) mod N^2 (binomial) — one mul, no modexp.
            let g_alpha = (Integer::one() + (&alpha * ek_n).complete()).modulo(ek_nn);
            let beta_n = pow_mod_signed(&beta, ek_n, ek_nn);
            (g_alpha * beta_n).modulo(ek_nn)
        };

        // w = h1^alpha * h2^gamma mod N_tilde
        let w = commitment_unknown_order(&ntilde.h1, &ntilde.h2, &ntilde.N_tilde, &alpha, &gamma);

        // Fiat-Shamir challenge
        let e = alice_challenge(ek_n, &g_paillier, cipher, &z, &u, &w);

        // Round 2: compute responses
        // s = r^e * beta mod N
        let s = {
            let r_e = pow_mod_signed(r, &e, ek_n);
            (r_e * &beta).modulo(ek_n)
        };
        // s1 = e*a + alpha
        let s1 = (&e * a).complete() + &alpha;
        // s2 = e*rho + gamma
        let s2 = (&e * &rho).complete() + &gamma;

        AliceProof { z, e, s, s1, s2 }
    }

    /// Verify Alice's range proof.
    ///
    /// # Parameters
    /// - `cipher`: the Paillier ciphertext $C$
    /// - `ek_n`: the Paillier modulus $N$
    /// - `ek_nn`: the Paillier modulus squared $N^2$
    /// - `ntilde`: the Ring-Pedersen auxiliary parameters
    ///
    /// # Errors
    /// Returns `MtaRangeError::AliceVerify` if the proof does not verify.
    pub fn verify<C>(
        &self,
        cipher: &Integer,
        ek_n: &Integer,
        ek_nn: &Integer,
        ntilde: &NTildeParams,
    ) -> Result<(), MtaRangeError>
    where
        C: TecdsaCurve,
        FieldBytesSize<C>: ModulusSize,
        <C as CurveArithmetic>::Scalar: PrimeField<Repr = FieldBytes<C>>,
    {
        let q = group_order_integer::<C>();
        let q3 = (&q * &q).complete() * &q;

        // Range check: s1 < q^3
        if self.s1 > q3 {
            return Err(MtaRangeError::AliceVerify);
        }

        // Reconstruct u: u = (1+N)^s1 * s^N * C^{-e} mod N^2
        let g_paillier = ek_n + Integer::one();
        let u = {
            // (1 + N)^s1 = (1 + s1*N) mod N^2 (binomial) — one mul, no modexp.
            let gs1 = (Integer::one() + (&self.s1 * ek_n).complete()).modulo(ek_nn);
            let s_n = pow_mod_signed(&self.s, ek_n, ek_nn);
            let neg_e = -self.e.clone();
            let c_neg_e = pow_mod_signed(cipher, &neg_e, ek_nn);
            (gs1 * s_n % ek_nn * c_neg_e).modulo(ek_nn)
        };

        // Reconstruct w: w = h1^s1 * h2^s2 * z^{-e} mod N_tilde
        let w = {
            let h1_s1 = pow_mod_signed(&ntilde.h1, &self.s1, &ntilde.N_tilde);
            let h2_s2 = pow_mod_signed(&ntilde.h2, &self.s2, &ntilde.N_tilde);
            let neg_e = -self.e.clone();
            let z_neg_e = pow_mod_signed(&self.z, &neg_e, &ntilde.N_tilde);
            (h1_s1 * h2_s2 % &ntilde.N_tilde * z_neg_e).modulo(&ntilde.N_tilde)
        };

        // Recompute challenge
        let e = alice_challenge(ek_n, &g_paillier, cipher, &self.z, &u, &w);

        if e != self.e {
            return Err(MtaRangeError::AliceVerify);
        }

        Ok(())
    }
}

/// Compute the Fiat-Shamir challenge for Alice's proof.
fn alice_challenge(
    N: &Integer,
    Gen: &Integer,
    cipher: &Integer,
    z: &Integer,
    u: &Integer,
    w: &Integer,
) -> Integer {
    let mut hasher = Sha256::new();
    hasher.update(N.to_bytes_msf());
    hasher.update(Gen.to_bytes_msf());
    hasher.update(cipher.to_bytes_msf());
    hasher.update(z.to_bytes_msf());
    hasher.update(u.to_bytes_msf());
    hasher.update(w.to_bytes_msf());
    Integer::from_bytes_msf(&hasher.finalize())
}

// ============================================================================
// Bob's proof
// ============================================================================

/// Non-interactive range proof that Bob's MtA ciphertext is correctly formed.
///
/// Bob knows $(b, \beta', r)$ s.t. $C_b = b \cdot C_a \oplus \text{Enc}_N(\beta'; r)$
/// and proves $|b| < q^3$.
///
/// **Statement:** $(C_a, C_b, N, N', h_1, h_2)$.
///
/// **Witness:** $(b, \beta', r)$.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BobProof {
    t: Integer,
    z: Integer,
    e: Integer,
    s: Integer,
    s1: Integer,
    s2: Integer,
    t1: Integer,
    t2: Integer,
}

impl BobProof {
    /// Generate Bob's range proof (without EC check).
    ///
    /// # Parameters
    /// - `a_encrypted`: Alice's ciphertext $C_a$
    /// - `mta_encrypted`: the MtA output ciphertext $C_b = b \cdot C_a \oplus \text{Enc}(\beta'; r)$
    /// - `b`: Bob's secret multiplier
    /// - `beta_prim`: the random value Bob adds (plaintext of the additive term)
    /// - `ek_n`: the Paillier modulus $N$
    /// - `ek_nn`: the Paillier modulus squared $N^2$
    /// - `ntilde`: the Ring-Pedersen auxiliary parameters
    /// - `r`: the Paillier encryption randomness used for $\text{Enc}(\beta')$
    /// - `rng`: a cryptographic RNG
    ///
    /// Returns `(proof, optional_u_point)`. When `check_ec` is true, `u_point`
    /// contains the blinding EC point needed for `BobProofExt`.
    #[allow(clippy::too_many_arguments)]
    pub fn prove<C>(
        a_encrypted: &Integer,
        mta_encrypted: &Integer,
        b: &Integer,
        beta_prim: &Integer,
        ek_n: &Integer,
        ek_nn: &Integer,
        ntilde: &NTildeParams,
        r: &Integer,
        check_ec: bool,
        rng: &mut impl rand_core::CryptoRngCore,
    ) -> (Self, Option<C::ProjectivePoint>)
    where
        C: TecdsaCurve,
        FieldBytesSize<C>: ModulusSize,
        <C as CurveArithmetic>::Scalar: PrimeField<Repr = FieldBytes<C>>,
        <C as CurveArithmetic>::ProjectivePoint: GroupEncoding,
    {
        let q = group_order_integer::<C>();
        let q3 = (&q * &q).complete() * &q;
        let q_N_tilde = (&q * &ntilde.N_tilde).complete();
        let q3_N_tilde = (&q3 * &ntilde.N_tilde).complete();
        let q2_N = (&q * &q).complete() * ek_n;

        // Round 1: sample blinding values
        let alpha = sample_below(&q3, rng);
        let beta = Integer::sample_in_mult_group_of(rng, ek_n);
        let gamma = sample_below(&q2_N, rng);
        let rho = sample_below(&q_N_tilde, rng);
        let rho_prim = sample_below(&q3_N_tilde, rng);
        let sigma = sample_below(&q_N_tilde, rng);
        let tau = sample_below(&q3_N_tilde, rng);

        // z = h1^b * h2^rho mod N_tilde
        let z = commitment_unknown_order(&ntilde.h1, &ntilde.h2, &ntilde.N_tilde, b, &rho);

        // z' = h1^alpha * h2^rho' mod N_tilde
        let z_prim =
            commitment_unknown_order(&ntilde.h1, &ntilde.h2, &ntilde.N_tilde, &alpha, &rho_prim);

        // t = h1^beta_prim * h2^sigma mod N_tilde
        let t =
            commitment_unknown_order(&ntilde.h1, &ntilde.h2, &ntilde.N_tilde, beta_prim, &sigma);

        // w = h1^gamma * h2^tau mod N_tilde
        let w_commit =
            commitment_unknown_order(&ntilde.h1, &ntilde.h2, &ntilde.N_tilde, &gamma, &tau);

        // v = C_a^alpha * (1 + gamma*N) * beta^N mod N^2
        let v = {
            let ca_alpha = pow_mod_signed(a_encrypted, &alpha, ek_nn);
            let g_gamma = ((&gamma * ek_n).complete() + Integer::one()).modulo(ek_nn);
            let beta_n = pow_mod_signed(&beta, ek_n, ek_nn);
            (ca_alpha * g_gamma % ek_nn * beta_n).modulo(ek_nn)
        };

        // Fiat-Shamir challenge
        let g_paillier = ek_n + Integer::one();
        let (e, check_u) = if check_ec {
            // Extended proof: include X = bG and u = alpha*G in the hash
            let b_scalar = integer_to_scalar::<C>(b);
            let alpha_scalar = integer_to_scalar::<C>(&alpha);
            let G = C::generator();
            let X = G * b_scalar;
            let u_point = G * alpha_scalar;
            let e = bob_challenge_ext::<C>(
                ek_n,
                &g_paillier,
                a_encrypted,
                mta_encrypted,
                &z,
                &z_prim,
                &t,
                &v,
                &w_commit,
                &X,
                &u_point,
            );
            (e, Some(u_point))
        } else {
            let e = bob_challenge(
                ek_n,
                &g_paillier,
                a_encrypted,
                mta_encrypted,
                &z,
                &z_prim,
                &t,
                &v,
                &w_commit,
            );
            (e, None)
        };

        // Round 2: compute responses
        let s = {
            let r_e = pow_mod_signed(r, &e, ek_n);
            (r_e * &beta).modulo(ek_n)
        };
        let s1 = (&e * b).complete() + &alpha;
        let s2 = (&e * &rho).complete() + &rho_prim;
        let t1 = (&e * beta_prim).complete() + &gamma;
        let t2 = (&e * &sigma).complete() + &tau;

        (
            BobProof {
                t,
                z,
                e,
                s,
                s1,
                s2,
                t1,
                t2,
            },
            check_u,
        )
    }

    /// Verify Bob's range proof (without EC check).
    ///
    /// # Parameters
    /// - `a_enc`: Alice's ciphertext $C_a$
    /// - `mta_out`: the MtA output ciphertext $C_b$
    /// - `ek_n`: the Paillier modulus $N$
    /// - `ek_nn`: the Paillier modulus squared $N^2$
    /// - `ntilde`: the Ring-Pedersen auxiliary parameters
    ///
    /// # Errors
    /// Returns `MtaRangeError::BobVerify` if the proof does not verify.
    pub fn verify<C>(
        &self,
        a_enc: &Integer,
        mta_out: &Integer,
        ek_n: &Integer,
        ek_nn: &Integer,
        ntilde: &NTildeParams,
    ) -> Result<(), MtaRangeError>
    where
        C: TecdsaCurve,
        FieldBytesSize<C>: ModulusSize,
        <C as CurveArithmetic>::Scalar: PrimeField<Repr = FieldBytes<C>>,
    {
        self.verify_inner::<C>(a_enc, mta_out, ek_n, ek_nn, ntilde, None)
    }

    /// Internal verification logic shared by `BobProof` and `BobProofExt`.
    fn verify_inner<C>(
        &self,
        a_enc: &Integer,
        mta_out: &Integer,
        ek_n: &Integer,
        ek_nn: &Integer,
        ntilde: &NTildeParams,
        check: Option<(&C::ProjectivePoint, &C::ProjectivePoint)>,
    ) -> Result<(), MtaRangeError>
    where
        C: TecdsaCurve,
        FieldBytesSize<C>: ModulusSize,
        <C as CurveArithmetic>::Scalar: PrimeField<Repr = FieldBytes<C>>,
        <C as CurveArithmetic>::ProjectivePoint: GroupEncoding,
    {
        let q = group_order_integer::<C>();
        let q3 = (&q * &q).complete() * &q;

        // Range check: s1 < q^3
        if self.s1 > q3 {
            return Err(MtaRangeError::BobVerify);
        }

        let neg_e = -self.e.clone();

        // Reconstruct z': z' = h1^s1 * h2^s2 * z^{-e} mod N_tilde
        let z_prim = {
            let h1_s1 = pow_mod_signed(&ntilde.h1, &self.s1, &ntilde.N_tilde);
            let h2_s2 = pow_mod_signed(&ntilde.h2, &self.s2, &ntilde.N_tilde);
            let z_neg_e = pow_mod_signed(&self.z, &neg_e, &ntilde.N_tilde);
            (h1_s1 * h2_s2 % &ntilde.N_tilde * z_neg_e).modulo(&ntilde.N_tilde)
        };

        // Reconstruct v: v = C_a^s1 * s^N * (1+t1*N) * C_b^{-e} mod N^2
        let v = {
            let ca_s1 = pow_mod_signed(a_enc, &self.s1, ek_nn);
            let s_n = pow_mod_signed(&self.s, ek_n, ek_nn);
            let g_t1 = ((&self.t1 * ek_n).complete() + Integer::one()).modulo(ek_nn);
            let mta_neg_e = pow_mod_signed(mta_out, &neg_e, ek_nn);
            (ca_s1 * s_n % ek_nn * g_t1 % ek_nn * mta_neg_e).modulo(ek_nn)
        };

        // Reconstruct w: w = h1^t1 * h2^t2 * t^{-e} mod N_tilde
        let w_commit = {
            let h1_t1 = pow_mod_signed(&ntilde.h1, &self.t1, &ntilde.N_tilde);
            let h2_t2 = pow_mod_signed(&ntilde.h2, &self.t2, &ntilde.N_tilde);
            let t_neg_e = pow_mod_signed(&self.t, &neg_e, &ntilde.N_tilde);
            (h1_t1 * h2_t2 % &ntilde.N_tilde * t_neg_e).modulo(&ntilde.N_tilde)
        };

        // Recompute challenge
        let g_paillier = ek_n + Integer::one();
        let e = match check {
            Some((X, u)) => bob_challenge_ext::<C>(
                ek_n,
                &g_paillier,
                a_enc,
                mta_out,
                &self.z,
                &z_prim,
                &self.t,
                &v,
                &w_commit,
                X,
                u,
            ),
            None => bob_challenge(
                ek_n,
                &g_paillier,
                a_enc,
                mta_out,
                &self.z,
                &z_prim,
                &self.t,
                &v,
                &w_commit,
            ),
        };

        if e != self.e {
            return Err(MtaRangeError::BobVerify);
        }

        Ok(())
    }
}

/// Compute the Fiat-Shamir challenge for Bob's basic proof.
#[allow(clippy::too_many_arguments)]
fn bob_challenge(
    N: &Integer,
    Gen: &Integer,
    a_enc: &Integer,
    mta_out: &Integer,
    z: &Integer,
    z_prim: &Integer,
    t: &Integer,
    v: &Integer,
    w: &Integer,
) -> Integer {
    let mut hasher = Sha256::new();
    hasher.update(N.to_bytes_msf());
    hasher.update(Gen.to_bytes_msf());
    hasher.update(a_enc.to_bytes_msf());
    hasher.update(mta_out.to_bytes_msf());
    hasher.update(z.to_bytes_msf());
    hasher.update(z_prim.to_bytes_msf());
    hasher.update(t.to_bytes_msf());
    hasher.update(v.to_bytes_msf());
    hasher.update(w.to_bytes_msf());
    Integer::from_bytes_msf(&hasher.finalize())
}

/// Compute the Fiat-Shamir challenge for Bob's extended proof (with EC check).
#[allow(clippy::too_many_arguments)]
fn bob_challenge_ext<C>(
    N: &Integer,
    Gen: &Integer,
    a_enc: &Integer,
    mta_out: &Integer,
    z: &Integer,
    z_prim: &Integer,
    t: &Integer,
    v: &Integer,
    w: &Integer,
    X: &C::ProjectivePoint,
    u: &C::ProjectivePoint,
) -> Integer
where
    C: CurveArithmetic,
    <C as CurveArithmetic>::ProjectivePoint: GroupEncoding,
{
    let mut hasher = Sha256::new();
    hasher.update(N.to_bytes_msf());
    hasher.update(Gen.to_bytes_msf());
    hasher.update(a_enc.to_bytes_msf());
    hasher.update(mta_out.to_bytes_msf());
    hasher.update(z.to_bytes_msf());
    hasher.update(z_prim.to_bytes_msf());
    hasher.update(t.to_bytes_msf());
    hasher.update(v.to_bytes_msf());
    hasher.update(w.to_bytes_msf());
    // Include EC points: X coordinates then Y coordinates
    // We use compressed encoding (GroupEncoding) for simplicity and correctness
    hasher.update(X.to_bytes().as_ref());
    hasher.update(u.to_bytes().as_ref());
    Integer::from_bytes_msf(&hasher.finalize())
}

// ============================================================================
// Bob's extended proof (with EC DLog check)
// ============================================================================

/// Bob's extended range proof, additionally proving $B = bG$ on the elliptic
/// curve. This is the "MtAwc" variant from GG18.
#[derive(Debug, Clone)]
pub struct BobProofExt<C: CurveArithmetic> {
    /// The underlying Bob proof.
    pub proof: BobProof,
    /// The blinding point $u = \alpha G$ (needed for EC verification).
    pub u: C::ProjectivePoint,
}

impl<C> Serialize for BobProofExt<C>
where
    C: CurveArithmetic,
    C::ProjectivePoint: GroupEncoding,
{
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut s = serializer.serialize_struct("BobProofExt", 2)?;
        s.serialize_field("proof", &self.proof)?;
        s.serialize_field("u", self.u.to_bytes().as_ref())?;
        s.end()
    }
}

impl<'de, C> Deserialize<'de> for BobProofExt<C>
where
    C: CurveArithmetic,
    C::ProjectivePoint: GroupEncoding,
{
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        #[derive(Deserialize)]
        struct Helper {
            proof: BobProof,
            u: Vec<u8>,
        }
        let h = Helper::deserialize(deserializer)?;
        let mut repr = <C::ProjectivePoint as GroupEncoding>::Repr::default();
        let repr_slice = repr.as_mut();
        if h.u.len() != repr_slice.len() {
            return Err(serde::de::Error::custom("invalid point length"));
        }
        repr_slice.copy_from_slice(&h.u);
        let point = Option::from(C::ProjectivePoint::from_bytes(&repr))
            .ok_or_else(|| serde::de::Error::custom("invalid point encoding"))?;
        Ok(BobProofExt {
            proof: h.proof,
            u: point,
        })
    }
}

impl<C> BobProofExt<C>
where
    C: TecdsaCurve,
    FieldBytesSize<C>: ModulusSize,
    <C as CurveArithmetic>::Scalar: PrimeField,
    <C as CurveArithmetic>::ProjectivePoint: GroupEncoding,
{
    /// Prove Bob's extended range proof.
    ///
    /// Same parameters as `BobProof::prove`, but always includes the EC check.
    #[allow(clippy::too_many_arguments)]
    pub fn prove(
        a_encrypted: &Integer,
        mta_encrypted: &Integer,
        b: &Integer,
        beta_prim: &Integer,
        ek_n: &Integer,
        ek_nn: &Integer,
        ntilde: &NTildeParams,
        r: &Integer,
        rng: &mut impl rand_core::CryptoRngCore,
    ) -> Self {
        let (proof, u) = BobProof::prove::<C>(
            a_encrypted,
            mta_encrypted,
            b,
            beta_prim,
            ek_n,
            ek_nn,
            ntilde,
            r,
            true,
            rng,
        );
        BobProofExt {
            proof,
            u: u.expect("check_ec=true always returns Some"),
        }
    }

    /// Verify Bob's extended range proof.
    ///
    /// # Parameters
    /// - `a_enc`: Alice's ciphertext $C_a$
    /// - `mta_out`: the MtA output ciphertext $C_b$
    /// - `ek_n`: the Paillier modulus $N$
    /// - `ek_nn`: $N^2$
    /// - `ntilde`: Ring-Pedersen auxiliary parameters
    /// - `X`: the claimed public key $X = bG$ (to be verified)
    ///
    /// # Errors
    /// Returns `MtaRangeError::BobVerify` if the proof does not verify.
    pub fn verify(
        &self,
        a_enc: &Integer,
        mta_out: &Integer,
        ek_n: &Integer,
        ek_nn: &Integer,
        ntilde: &NTildeParams,
        X: &C::ProjectivePoint,
    ) -> Result<(), MtaRangeError> {
        // First verify the underlying Bob proof with EC hash
        self.proof
            .verify_inner::<C>(a_enc, mta_out, ek_n, ek_nn, ntilde, Some((X, &self.u)))?;

        // EC check: s1 * G == e * X + u
        let s1_scalar = integer_to_scalar::<C>(&self.proof.s1);
        let e_scalar = integer_to_scalar::<C>(&self.proof.e);
        let G = C::generator();
        let lhs = G * s1_scalar;
        let rhs = *X * e_scalar + self.u;

        if lhs.to_bytes().as_ref() != rhs.to_bytes().as_ref() {
            return Err(MtaRangeError::BobVerify);
        }

        Ok(())
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    type TestCurve = k256::Secp256k1;

    #[test]
    #[ignore = "perf micro-benchmark for B2b; run with --ignored --nocapture"]
    fn paillier_g_pow_linear_vs_modexp() {
        use std::time::Instant;
        // ~3072-bit odd modulus N (primality irrelevant to timing); N^2 ~6144-bit.
        let n: Integer = (Integer::one() << 3072) - Integer::one(); // ~3072-bit odd
        let nn: Integer = (&n * &n).complete();
        let g = &n + Integer::one(); // 1 + N
        let alpha = (Integer::one() << 768) - Integer::one(); // ~768-bit exponent
        const ITERS: u32 = 200;

        let t0 = Instant::now();
        for _ in 0..ITERS {
            let _ = pow_mod_signed(&g, &alpha, &nn);
        }
        let t_modexp = t0.elapsed() / ITERS;

        let t1 = Instant::now();
        for _ in 0..ITERS {
            let _ = (Integer::one() + (&alpha * &n).complete()).modulo(&nn);
        }
        let t_linear = t1.elapsed() / ITERS;

        println!(
            "B2b (1+N)^x: modexp={t_modexp:>10.3?}  linear={t_linear:>10.3?}  speedup={:.0}x",
            t_modexp.as_secs_f64() / t_linear.as_secs_f64().max(1e-12)
        );
    }

    /// Set up Paillier keys for testing (small primes for speed).
    fn setup_paillier(
        rng: &mut impl rand_core::CryptoRngCore,
    ) -> (fast_paillier::DecryptionKey, fast_paillier::EncryptionKey) {
        let p = Integer::generate_safe_prime(rng, 256);
        let q = Integer::generate_safe_prime(rng, 256);
        let dk = fast_paillier::DecryptionKey::from_primes(p, q).expect("valid primes");
        let ek = dk.encryption_key().clone();
        (dk, ek)
    }

    /// Set up Ring-Pedersen auxiliary parameters $(N', h_1, h_2)$.
    fn setup_ntilde(rng: &mut impl rand_core::CryptoRngCore) -> NTildeParams {
        let p = Integer::generate_safe_prime(rng, 256);
        let q = Integer::generate_safe_prime(rng, 256);
        let n_tilde = (&p * &q).complete();

        // h1 = random element in Z*_{N'}
        let h1 = Integer::sample_in_mult_group_of(rng, &n_tilde);

        // h2 = h1^lambda mod N' for random lambda coprime to phi(N')
        let phi_n = (&p - Integer::one()) * (&q - Integer::one());
        let lambda = sample_below(&phi_n, rng);
        let h2 = h1
            .pow_mod_ref(&lambda, &n_tilde)
            .expect("pow_mod defined")
            .complete();

        NTildeParams {
            N_tilde: n_tilde,
            h1,
            h2,
        }
    }

    // ---- Alice proof tests ----

    #[test]
    fn alice_proof_honest_verifies() {
        let mut rng = rand::thread_rng();
        let (_dk, ek) = setup_paillier(&mut rng);
        let ntilde = setup_ntilde(&mut rng);

        // Alice's secret: a small value in [1, q)
        let q = group_order_integer::<TestCurve>();
        let a = sample_below(&q, &mut rng);

        // Encrypt a
        let (cipher, r) = ek.encrypt_with_random(&mut rng, &a).expect("encrypt");

        let proof =
            AliceProof::prove::<TestCurve>(&a, &cipher, ek.n(), ek.nn(), &ntilde, &r, &mut rng);

        proof
            .verify::<TestCurve>(&cipher, ek.n(), ek.nn(), &ntilde)
            .expect("honest Alice proof should verify");
    }

    #[test]
    #[ignore = "redundant negative/boundary test"]
    fn alice_proof_wrong_a_rejects() {
        let mut rng = rand::thread_rng();
        let (_dk, ek) = setup_paillier(&mut rng);
        let ntilde = setup_ntilde(&mut rng);

        let q = group_order_integer::<TestCurve>();
        let a = sample_below(&q, &mut rng);
        let (cipher, _r) = ek.encrypt_with_random(&mut rng, &a).expect("encrypt");

        // Use a wrong `a` in the proof (different from what was encrypted)
        let wrong_a = sample_below(&q, &mut rng);
        let wrong_r = Integer::sample_in_mult_group_of(&mut rng, ek.n());

        let proof = AliceProof::prove::<TestCurve>(
            &wrong_a,
            &cipher,
            ek.n(),
            ek.nn(),
            &ntilde,
            &wrong_r,
            &mut rng,
        );

        assert!(
            proof
                .verify::<TestCurve>(&cipher, ek.n(), ek.nn(), &ntilde)
                .is_err(),
            "Alice proof with wrong a should fail"
        );
    }

    // ---- Bob proof tests ----

    #[test]
    #[ignore = "redundant negative/boundary test"]
    fn bob_proof_honest_verifies() {
        let mut rng = rand::thread_rng();
        let (_dk, ek) = setup_paillier(&mut rng);
        let ntilde = setup_ntilde(&mut rng);

        let q = group_order_integer::<TestCurve>();

        // Alice encrypts her secret
        let a = sample_below(&q, &mut rng);
        let (enc_a, _r_a) = ek.encrypt_with_random(&mut rng, &a).expect("encrypt a");

        // Bob's secret
        let b = sample_below(&q, &mut rng);

        // Bob computes MtA: C_b = b * C_a + Enc(beta_prim)
        let beta_prim = sample_below(ek.half_n(), &mut rng);
        let r_bob = Integer::sample_in_mult_group_of(&mut rng, ek.n());

        let b_times_enc_a = ek.omul(&b, &enc_a).expect("omul");
        let enc_beta = ek.encrypt_with(&beta_prim, &r_bob).expect("encrypt beta");
        let mta_out = ek.oadd(&b_times_enc_a, &enc_beta).expect("oadd");

        let (proof, _) = BobProof::prove::<TestCurve>(
            &enc_a,
            &mta_out,
            &b,
            &beta_prim,
            ek.n(),
            ek.nn(),
            &ntilde,
            &r_bob,
            false,
            &mut rng,
        );

        proof
            .verify::<TestCurve>(&enc_a, &mta_out, ek.n(), ek.nn(), &ntilde)
            .expect("honest Bob proof should verify");
    }

    #[test]
    #[ignore = "redundant negative/boundary test"]
    fn bob_proof_wrong_b_rejects() {
        let mut rng = rand::thread_rng();
        let (_dk, ek) = setup_paillier(&mut rng);
        let ntilde = setup_ntilde(&mut rng);

        let q = group_order_integer::<TestCurve>();

        // Alice encrypts her secret
        let a = sample_below(&q, &mut rng);
        let (enc_a, _r_a) = ek.encrypt_with_random(&mut rng, &a).expect("encrypt a");

        // Bob's real secret
        let b = sample_below(&q, &mut rng);

        // Bob computes MtA correctly
        let beta_prim = sample_below(ek.half_n(), &mut rng);
        let r_bob = Integer::sample_in_mult_group_of(&mut rng, ek.n());

        let b_times_enc_a = ek.omul(&b, &enc_a).expect("omul");
        let enc_beta = ek.encrypt_with(&beta_prim, &r_bob).expect("encrypt beta");
        let mta_out = ek.oadd(&b_times_enc_a, &enc_beta).expect("oadd");

        // Prove with wrong b
        let wrong_b = sample_below(&q, &mut rng);

        let (proof, _) = BobProof::prove::<TestCurve>(
            &enc_a,
            &mta_out,
            &wrong_b,
            &beta_prim,
            ek.n(),
            ek.nn(),
            &ntilde,
            &r_bob,
            false,
            &mut rng,
        );

        assert!(
            proof
                .verify::<TestCurve>(&enc_a, &mta_out, ek.n(), ek.nn(), &ntilde)
                .is_err(),
            "Bob proof with wrong b should fail"
        );
    }

    // ---- Bob extended proof tests ----

    #[test]
    fn bob_ext_proof_honest_verifies() {
        let mut rng = rand::thread_rng();
        let (_dk, ek) = setup_paillier(&mut rng);
        let ntilde = setup_ntilde(&mut rng);

        let q = group_order_integer::<TestCurve>();

        // Alice encrypts her secret
        let a = sample_below(&q, &mut rng);
        let (enc_a, _r_a) = ek.encrypt_with_random(&mut rng, &a).expect("encrypt a");

        // Bob's secret
        let b = sample_below(&q, &mut rng);

        // X = bG
        let b_scalar = integer_to_scalar::<TestCurve>(&b);
        let G = <TestCurve as CurveArithmetic>::ProjectivePoint::GENERATOR;
        let X = G * b_scalar;

        // Bob computes MtA
        let beta_prim = sample_below(ek.half_n(), &mut rng);
        let r_bob = Integer::sample_in_mult_group_of(&mut rng, ek.n());

        let b_times_enc_a = ek.omul(&b, &enc_a).expect("omul");
        let enc_beta = ek.encrypt_with(&beta_prim, &r_bob).expect("encrypt beta");
        let mta_out = ek.oadd(&b_times_enc_a, &enc_beta).expect("oadd");

        let proof = BobProofExt::<TestCurve>::prove(
            &enc_a,
            &mta_out,
            &b,
            &beta_prim,
            ek.n(),
            ek.nn(),
            &ntilde,
            &r_bob,
            &mut rng,
        );

        proof
            .verify(&enc_a, &mta_out, ek.n(), ek.nn(), &ntilde, &X)
            .expect("honest Bob extended proof should verify");
    }

    #[test]
    #[ignore = "redundant negative/boundary test"]
    fn bob_ext_proof_wrong_b_rejects() {
        let mut rng = rand::thread_rng();
        let (_dk, ek) = setup_paillier(&mut rng);
        let ntilde = setup_ntilde(&mut rng);

        let q = group_order_integer::<TestCurve>();

        // Alice encrypts her secret
        let a = sample_below(&q, &mut rng);
        let (enc_a, _r_a) = ek.encrypt_with_random(&mut rng, &a).expect("encrypt a");

        // Bob's real secret
        let b = sample_below(&q, &mut rng);

        // X = bG (correct public key)
        let b_scalar = integer_to_scalar::<TestCurve>(&b);
        let G = <TestCurve as CurveArithmetic>::ProjectivePoint::GENERATOR;
        let X = G * b_scalar;

        // Bob computes MtA correctly
        let beta_prim = sample_below(ek.half_n(), &mut rng);
        let r_bob = Integer::sample_in_mult_group_of(&mut rng, ek.n());

        let b_times_enc_a = ek.omul(&b, &enc_a).expect("omul");
        let enc_beta = ek.encrypt_with(&beta_prim, &r_bob).expect("encrypt beta");
        let mta_out = ek.oadd(&b_times_enc_a, &enc_beta).expect("oadd");

        // Prove with wrong b (X won't match)
        let wrong_b = sample_below(&q, &mut rng);

        let proof = BobProofExt::<TestCurve>::prove(
            &enc_a,
            &mta_out,
            &wrong_b,
            &beta_prim,
            ek.n(),
            ek.nn(),
            &ntilde,
            &r_bob,
            &mut rng,
        );

        assert!(
            proof
                .verify(&enc_a, &mta_out, ek.n(), ek.nn(), &ntilde, &X)
                .is_err(),
            "Bob extended proof with wrong b should fail"
        );
    }

    /// Reproduce the failure with 512-bit primes (same as GG18 integration tests).
    #[test]
    #[ignore = "redundant negative/boundary test"]
    fn bob_ext_proof_512bit_primes() {
        let mut rng = rand::thread_rng();

        // 512-bit primes (N ~ 1024 bits) — same as GG18 sign tests
        let p = Integer::generate_safe_prime(&mut rng, 512);
        let q = Integer::generate_safe_prime(&mut rng, 512);
        let dk = fast_paillier::DecryptionKey::from_primes(p, q).expect("valid primes");
        let ek = dk.encryption_key().clone();

        let ntilde = setup_ntilde(&mut rng);

        let q_order = group_order_integer::<TestCurve>();

        let a = sample_below(&q_order, &mut rng);
        let (enc_a, _r_a) = ek.encrypt_with_random(&mut rng, &a).expect("encrypt a");

        let b = sample_below(&q_order, &mut rng);

        let b_scalar = integer_to_scalar::<TestCurve>(&b);
        let G = <TestCurve as CurveArithmetic>::ProjectivePoint::GENERATOR;
        let X = G * b_scalar;

        let beta_prim = sample_below(ek.half_n(), &mut rng);
        let r_bob = Integer::sample_in_mult_group_of(&mut rng, ek.n());

        let b_times_enc_a = ek.omul(&b, &enc_a).expect("omul");
        let enc_beta = ek.encrypt_with(&beta_prim, &r_bob).expect("encrypt beta");
        let mta_out = ek.oadd(&b_times_enc_a, &enc_beta).expect("oadd");

        let proof = BobProofExt::<TestCurve>::prove(
            &enc_a,
            &mta_out,
            &b,
            &beta_prim,
            ek.n(),
            ek.nn(),
            &ntilde,
            &r_bob,
            &mut rng,
        );

        proof
            .verify(&enc_a, &mta_out, ek.n(), ek.nn(), &ntilde, &X)
            .expect("Bob ext proof with 512-bit primes should verify");
    }
}
