[package]
name = "tecdsa-paillier"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Paillier encryption wrapper for tecdsa"

[dependencies]
rug = { workspace = true }
tecdsa-core = { workspace = true }
tecdsa-bigint = { workspace = true }
tecdsa-commit = { workspace = true }
tecdsa-curve = { workspace = true, features = ["secp256k1"] }
tecdsa-pedersen-mod = { workspace = true }
tecdsa-protocol = { workspace = true }
fast-paillier = { workspace = true, features = ["serde"] }
paillier-zk = { workspace = true }
elliptic-curve = { workspace = true }
generic-ec = { workspace = true }
k256 = { workspace = true }
rand_core = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
udigest.workspace = true
zeroize = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
bincode = { workspace = true }

[lints]
workspace = true
