// SPDX-License-Identifier: MIT OR Apache-2.0
//! Setup data for ABC+24: Paillier key + Damgard-Fujisaki parameters.
//!
//! In the full protocol (Section 4.2), the server generates this once and
//! reuses it across all clients. The setup includes:
//! - Paillier modulus N and a canonical base rho in Z*_{N^2}
//! - Damgard-Fujisaki commitment parameters (N_hat, t, s1, s2)
//! - Pedersen EC commitment generators (h, f)
//! - ZK proofs of well-formedness (pi_mod, pi_fac, pi_df)
//!
//! For the simplified (trusted-dealer) implementation, we construct
//! SetupData directly from the Paillier key pair without the full
//! proof machinery.

use tecdsa_paillier::EncryptionKey;

/// Public setup parameters generated by the server.
///
/// Per Algorithm 4: `SetupData = (N, N_hat, rho, t, s1, s2, h, f, pi_mod, pi_fac, pi_df)`.
///
/// In our simplified implementation, we store the essential cryptographic
/// material and omit the one-time setup proofs (pi_mod, pi_fac, pi_df)
/// since we use trusted dealer keygen.
#[derive(Clone)]
pub struct SetupData {
    /// Paillier encryption key (contains modulus N).
    pub ek: EncryptionKey,
}

impl SetupData {
    #[must_use]
    pub fn from_ek(ek: &EncryptionKey) -> Self {
        Self { ek: ek.clone() }
    }
}
