[package]
name = "tecdsa-class-group"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "MIT OR Apache-2.0"
repository.workspace = true
description = "Class-group encryption and proofs for tecdsa"

[dependencies]
tecdsa-core = { workspace = true }
tecdsa-bigint = { workspace = true }
thiserror = { workspace = true }
gmp-mpfr-sys = { workspace = true }
rug = { workspace = true }
rand_core = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
k256 = { workspace = true }
elliptic-curve = { workspace = true }
zeroize = { workspace = true }
subtle = { workspace = true }
tecdsa-curve = { workspace = true, features = ["secp256k1"] }
tecdsa-protocol = { workspace = true }
tecdsa-vss = { workspace = true }

[dev-dependencies]
rand = { workspace = true }

[features]
gmp-hgcd = []
